# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-30 04:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Equity', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perform_metric',
            name='sharpeRatio',
            field=models.DecimalField(decimal_places=5, max_digits=7),
        ),
    ]
