# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-12 06:43
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Equity', '0002_auto_20171030_0947'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_investment_futures',
            name='username',
        ),
        migrations.RemoveField(
            model_name='user_investment_options',
            name='username',
        ),
        migrations.RemoveField(
            model_name='user_investment_record_futures',
            name='username',
        ),
        migrations.RemoveField(
            model_name='user_investment_record_options',
            name='username',
        ),
        migrations.AddField(
            model_name='user_investment_futures',
            name='user',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user_investment_options',
            name='user',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user_investment_record_futures',
            name='user',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user_investment_record_options',
            name='user',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
