# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-12 22:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Equity', '0004_auto_20171113_0404'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User_Investment_Futures',
            new_name='UserFutures',
        ),
        migrations.RenameModel(
            old_name='User_Investment_Options',
            new_name='UserOptions',
        ),
        migrations.RenameModel(
            old_name='User_Investment_Record_Futures',
            new_name='UserRecordFutures',
        ),
        migrations.RenameModel(
            old_name='User_Investment_Record_Options',
            new_name='UserRecordOptions',
        ),
    ]
