# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-12 22:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Equity', '0005_auto_20171113_0412'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userfutures',
            name='buy_price',
        ),
        migrations.RemoveField(
            model_name='useroptions',
            name='buy_price',
        ),
        migrations.RemoveField(
            model_name='userrecordfutures',
            name='buy_price',
        ),
        migrations.RemoveField(
            model_name='userrecordfutures',
            name='sold_price',
        ),
        migrations.RemoveField(
            model_name='userrecordoptions',
            name='buy_price',
        ),
        migrations.RemoveField(
            model_name='userrecordoptions',
            name='sold_price',
        ),
    ]
